

spring:
  application:
    name: Malus-Domestica
    
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${Db}
    password: ${Pwd}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true